// const { Head } = require("next/head");
// const { HomePage } = require("./home/index.js");
import { restoreFromLocalStorage } from '@/reducers/QuizSlice.js';
import Head from 'next/head.js';
import { useEffect, useRef } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import HomePage from './home/index.js';

export default function Home() {
  const initialized = useRef(false);
  const quizState = useSelector((state) => state.quiz);

  const dispatch = useDispatch();

  useEffect(() => {
    if (initialized.current) {
      localStorage.setItem('quiz', JSON.stringify(quizState));
    }
  }, [quizState]);

  useEffect(() => {
    if (!initialized.current) {
      const storedStateString = localStorage.getItem('quiz');
      if (storedStateString) {
        try {
          dispatch(restoreFromLocalStorage(JSON.parse(storedStateString)));
        } catch (_) {}
      }
      initialized.current = true;
    }
  }, []);

  return (
    <>
      <Head>
        <title>Stellar Sleep Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </>
  );
}
