// const { Head } = require("next/head");
// const { HomePage } = require("./home/index.js");
import { restoreFromLocalStorage, setUrlParams } from '@/reducers/QuizSlice.js';
import Head from 'next/head.js';
import { useRouter } from 'next/router.js';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import HomePage from './home/index.js';

export default function Home() {
  const [initialized, setInitialized] = useState(false);

  const dispatch = useDispatch();
  const router = useRouter();

  function saveUrlParams() {
    dispatch(setUrlParams(router.query));
  }

  useEffect(() => {
    if (!router.query) return;
    const storedStateString = localStorage.getItem('quiz');
    if (storedStateString) {
      try {
        dispatch(restoreFromLocalStorage(JSON.parse(storedStateString)));
      } catch (_) {}
    }
    saveUrlParams();
    setInitialized(true);
  }, [router.query]);

  return (
    <>
      <Head>
        <title>Stellar Sleep Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </>
  );
}
